### ISSUE TITLE
perf: use accurate sleep timing mechanism

### ISSUE THREAD

**Issue by lloydlobo** [lloydlobo/keystrokes#1]
https://github.com/lloydlobo/keystrokes/blob/ac42dfb176a64f5d8aee99bfd95d7c9715bc4435/src/app.py#L229

Instead of using time.sleep() for the animation delay, we can utilize a more accurate timing mechanism, such as the time.perf_counter() function.

This function provides a higher resolution timer, allowing for more precise frame timing. 

Replace the sleep(curr_time + FRAME_DELAY - time()) line with the following code:

```
from time import perf_counter

elapsed_time = perf_counter() - curr_time
remaining_time = FRAME_DELAY - elapsed_time
if remaining_time > 0:
    sleep(remaining_time)

```

OR without perf_counter:

```
elapsed_time = time() - curr_time
if elapsed_time < FRAME_DELAY:
    sleep_time = FRAME_DELAY - elapsed_time
    sleep(sleep_time)
```

**Comment by Harshal662** [comment]
plz assign it to me.
